// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtyDOu45lccPcJhke8ZEMotiEtP9zxFHQ',
    appId: '1:149659911631:web:58a16a2d94626aba50feba',
    messagingSenderId: '149659911631',
    projectId: 'watch-hub-7472a',
    authDomain: 'watch-hub-7472a.firebaseapp.com',
    storageBucket: 'watch-hub-7472a.firebasestorage.app',
    measurementId: 'G-FH4T379SBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzL2z1xhuglYx4-NHzqOYiFE5910Y8To',
    appId: '1:149659911631:android:bc4c5de76d9bdab950feba',
    messagingSenderId: '149659911631',
    projectId: 'watch-hub-7472a',
    storageBucket: 'watch-hub-7472a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MVIq2c8PgxPVLKTBlOtckwfAnOMx1Ic',
    appId: '1:149659911631:ios:113dd1de3fed033d50feba',
    messagingSenderId: '149659911631',
    projectId: 'watch-hub-7472a',
    storageBucket: 'watch-hub-7472a.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MVIq2c8PgxPVLKTBlOtckwfAnOMx1Ic',
    appId: '1:149659911631:ios:113dd1de3fed033d50feba',
    messagingSenderId: '149659911631',
    projectId: 'watch-hub-7472a',
    storageBucket: 'watch-hub-7472a.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtyDOu45lccPcJhke8ZEMotiEtP9zxFHQ',
    appId: '1:149659911631:web:58a16a2d94626aba50feba',
    messagingSenderId: '149659911631',
    projectId: 'watch-hub-7472a',
    authDomain: 'watch-hub-7472a.firebaseapp.com',
    storageBucket: 'watch-hub-7472a.firebasestorage.app',
    measurementId: 'G-FH4T379SBC',
  );
}
